[[plugins]]
repo   = 'Shougo/unite.vim'

# unite.vim を読み込んだら一緒に読み込む
[[plugins]]
repo      = 'Shougo/neomru.vim'
on_source = ['unite.vim']


# go
[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

# toml
[[plugins]]
repo  = 'cespare/vim-toml'
on_ft = 'toml'

# yaml
[[plugins]]
repo  = 'stephpy/vim-yaml'
on_ft = 'yaml'

# Markdown
[[plugins]]
repo  = 'plasticboy/vim-markdown'
on_ft = ['markdown', 'mkd']
hook_add = '''
    let g:vim_markdown_folding_disabled = 1
'''
