[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'vim-syntastic/syntastic'
hook_add = '''
    let g:syntastic_python_checkers = ["flake8"]
'''
