[hostname]
ssh_only = false
format = "[$hostname](bold gray) "
disabled = false

[directory]
truncation_length = 10
truncate_to_repo = false

[aws]
disabled = true

[gcloud]
disabled = true

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "gray"

[terraform]
format = "via [$symbol$version $workspace]($style) "
