[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'ujihisa/unite-colorscheme'

[[plugins]]
repo = 'w0rp/ale'
hook_add = 'source ~/.vim/rc/plugins/ale.rc.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = 'source ~/.vim/rc/plugins/indentline.rc.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.vim/rc/plugins/lightline.rc.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'
